spring:
  mail:
    host: smtp.163.com
    username: 18904183715@163.com
    password: BXqhLLSriFdPYpwY
  rabbitmq:
    host: 192.168.125.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /test
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  datasource:
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cc
  amqp:
    deserialization:
      allowed-list-patterns:
        - "java.util.ArrayList"
        - "java.util.HashMap"