spring:
  mail:
    host: smtp.163.com
    username: 18904183715@163.com
    password: ZCqvB9BTqBC8UxWk
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  datasource:
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cc